apiVersion: v1
kind: Service
metadata:
  name: backend-service
  labels:
    app: backend
spec:
  selector:
    app: backend
  ports:
    - port: 8080          # Port the Service exposes inside the cluster
      targetPort: 8080    # Container port
  type: ClusterIP         # Use LoadBalancer if you need external access
