apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  labels:
    app: frontend
spec:
  selector:
    app: frontend
  ports:
    - port: 8080           # Cluster IP port
      targetPort: 8080     # Container port
  type: ClusterIP        # Change to LoadBalancer/NodePort for external access
